import { fold } from "./text";
import type { Entity, EntityKind } from "./intel-types";
import type { LaneId } from "./types";

/**
 * Static gazetteer for the intelligence layer: countries, companies,
 * commodities, organisations and topics with folded EN and FR aliases.
 * Data only: matching lives in entities.ts. Aliases are written folded
 * (lowercase, no diacritics) and folded again at build time as a guard.
 * Two-letter aliases ("us", "eu", "bp") are matched case-sensitively on the
 * raw text by the extractor, so they never collide with ordinary words.
 */

const KIND_ORDER: EntityKind[] = ["country", "company", "commodity", "org", "topic"];

function make(kind: EntityKind, id: string, label: string, aliases: string[], extra: Partial<Entity> = {}): Entity {
  const seen = new Set<string>();
  const list: string[] = [];
  for (const a of [fold(label), ...aliases]) {
    const f = fold(a).trim();
    if (f && !seen.has(f)) {
      seen.add(f);
      list.push(f);
    }
  }
  return { id, kind, label, aliases: list, ...extra };
}

const country = (iso2: string, label: string, lat: number, lng: number, aliases: string[] = []): Entity =>
  make("country", iso2.toLowerCase(), label, aliases, { iso2: iso2.toUpperCase(), lat, lng });

const company = (id: string, label: string, iso2: string, sector: LaneId, aliases: string[] = []): Entity =>
  make("company", id, label, aliases, { iso2, sector });

const commodity = (id: string, label: string, sector: LaneId, aliases: string[]): Entity =>
  make("commodity", id, label, aliases, { sector });

const org = (id: string, label: string, aliases: string[], extra: Partial<Entity> = {}): Entity =>
  make("org", id, label, aliases, extra);

const topic = (id: string, label: string, sector: LaneId, aliases: string[]): Entity =>
  make("topic", id, label, aliases, { sector });

// ------------------------------------------------------------------ Countries

const COUNTRIES: Entity[] = [
  // Africa
  country("DZ", "Algeria", 28.0, 1.7, ["algerie", "algerian", "algerien", "algerienne", "algiers", "alger", "hassi messaoud", "arzew", "skikda"]),
  country("AO", "Angola", -12.5, 18.5, ["angolan", "angolais", "luanda", "cabinda"]),
  country("BJ", "Benin", 9.3, 2.3, ["beninois", "cotonou", "porto-novo"]),
  country("BW", "Botswana", -22.3, 24.7, ["gaborone"]),
  country("BF", "Burkina Faso", 12.2, -1.6, ["burkina", "burkinabe", "ouagadougou"]),
  country("BI", "Burundi", -3.4, 29.9, ["gitega", "bujumbura"]),
  country("CV", "Cabo Verde", 16.0, -24.0, ["cape verde", "cap-vert", "praia"]),
  country("CM", "Cameroon", 5.7, 12.7, ["cameroun", "cameroonian", "camerounais", "yaounde", "douala", "kribi"]),
  country("CF", "Central African Republic", 6.6, 20.9, ["centrafrique", "republique centrafricaine", "bangui"]),
  country("TD", "Chad", 15.5, 18.7, ["tchad", "chadian", "tchadien", "n'djamena", "ndjamena"]),
  country("KM", "Comoros", -11.9, 43.9, ["comores", "moroni"]),
  country("CG", "Republic of the Congo", -0.7, 15.6, ["congo-brazzaville", "brazzaville", "pointe-noire", "pointe noire"]),
  country("CD", "DR Congo", -2.9, 23.7, ["congo", "drc", "rdc", "democratic republic of congo", "democratic republic of the congo", "republique democratique du congo", "kinshasa", "congolese", "congolais", "katanga", "lubumbashi", "kolwezi"]),
  country("CI", "Cote d'Ivoire", 7.5, -5.5, ["ivory coast", "cote d ivoire", "ivorian", "ivoirien", "abidjan", "yamoussoukro"]),
  country("DJ", "Djibouti", 11.8, 42.6, ["djiboutian"]),
  country("EG", "Egypt", 26.8, 30.8, ["egypte", "egyptian", "egyptien", "egyptienne", "cairo", "le caire", "zohr", "damietta", "idku"]),
  country("GQ", "Equatorial Guinea", 1.7, 10.5, ["guinee equatoriale", "malabo", "bata"]),
  country("ER", "Eritrea", 15.2, 39.8, ["erythree", "asmara"]),
  country("SZ", "Eswatini", -26.5, 31.5, ["swaziland", "mbabane"]),
  country("ET", "Ethiopia", 9.1, 40.5, ["ethiopie", "ethiopian", "ethiopien", "addis ababa", "addis-abeba"]),
  country("GA", "Gabon", -0.8, 11.6, ["gabonese", "gabonais", "libreville", "port-gentil"]),
  country("GM", "Gambia", 13.4, -15.3, ["gambie", "banjul"]),
  country("GH", "Ghana", 7.9, -1.0, ["ghanaian", "ghaneen", "accra", "tema"]),
  country("GN", "Guinea", 9.9, -11.3, ["guinee", "guinean", "guineen", "conakry", "simandou"]),
  country("GW", "Guinea-Bissau", 12.0, -15.0, ["guinee-bissau", "bissau"]),
  country("KE", "Kenya", 0.0, 37.9, ["kenyan", "nairobi", "mombasa"]),
  country("LS", "Lesotho", -29.6, 28.2, ["maseru"]),
  country("LR", "Liberia", 6.4, -9.4, ["liberian", "liberien", "monrovia"]),
  country("LY", "Libya", 26.3, 17.2, ["libye", "libyan", "libyen", "libyenne", "tripoli", "benghazi", "noc libya", "sharara", "el feel"]),
  country("MG", "Madagascar", -18.8, 46.9, ["malagasy", "malgache", "antananarivo"]),
  country("MW", "Malawi", -13.3, 34.3, ["lilongwe"]),
  country("ML", "Mali", 17.6, -4.0, ["malian", "malien", "bamako"]),
  country("MR", "Mauritania", 20.3, -10.9, ["mauritanie", "mauritanian", "mauritanien", "nouakchott"]),
  country("MU", "Mauritius", -20.3, 57.6, ["maurice", "ile maurice", "port louis"]),
  country("MA", "Morocco", 31.8, -7.1, ["maroc", "moroccan", "marocain", "marocaine", "rabat", "casablanca", "tanger", "tangier", "tanger med", "guelmim", "dakhla"]),
  country("MZ", "Mozambique", -18.7, 35.5, ["mozambican", "mozambicain", "maputo", "cabo delgado", "rovuma"]),
  country("NA", "Namibia", -22.9, 18.5, ["namibie", "namibian", "namibien", "windhoek", "walvis bay", "orange basin"]),
  country("NE", "Niger", 17.6, 8.1, ["nigerien", "niamey"]),
  country("NG", "Nigeria", 9.1, 8.7, ["nigerian", "nigerians", "nigerian", "nigeriane", "abuja", "lagos", "port harcourt", "niger delta", "bonny", "nlng"]),
  country("RW", "Rwanda", -1.9, 29.9, ["rwandan", "rwandais", "kigali"]),
  country("ST", "Sao Tome and Principe", 0.2, 6.6, ["sao tome", "sao tome-et-principe"]),
  country("SN", "Senegal", 14.5, -14.5, ["senegalese", "senegalais", "dakar", "sangomar", "grand tortue"]),
  country("SC", "Seychelles", -4.7, 55.5, ["victoria seychelles"]),
  country("SL", "Sierra Leone", 8.5, -11.8, ["freetown"]),
  country("SO", "Somalia", 5.2, 46.2, ["somalie", "somali", "somalien", "mogadishu", "mogadiscio", "somaliland"]),
  country("ZA", "South Africa", -30.6, 22.9, ["afrique du sud", "south african", "sud-africain", "sud-africaine", "pretoria", "johannesburg", "cape town", "le cap", "durban", "richards bay", "eskom"]),
  country("SS", "South Sudan", 6.9, 31.3, ["soudan du sud", "juba"]),
  country("SD", "Sudan", 12.9, 30.2, ["soudan", "sudanese", "soudanais", "khartoum", "port sudan"]),
  country("TZ", "Tanzania", -6.4, 34.9, ["tanzanie", "tanzanian", "tanzanien", "dodoma", "dar es salaam"]),
  country("TG", "Togo", 8.6, 1.0, ["togolese", "togolais", "lome"]),
  country("TN", "Tunisia", 33.9, 9.5, ["tunisie", "tunisian", "tunisien", "tunisienne", "tunis"]),
  country("UG", "Uganda", 1.4, 32.3, ["ouganda", "ugandan", "ougandais", "kampala", "lake albert"]),
  country("ZM", "Zambia", -13.1, 27.8, ["zambie", "zambian", "zambien", "lusaka", "copperbelt"]),
  country("ZW", "Zimbabwe", -19.0, 29.2, ["zimbabwean", "zimbabween", "harare"]),
  // Americas
  country("AG", "Antigua and Barbuda", 17.1, -61.8, ["antigua", "antigua-et-barbuda"]),
  country("AR", "Argentina", -38.4, -63.6, ["argentine", "argentinian", "argentinian", "argentin", "buenos aires", "vaca muerta", "milei"]),
  country("BS", "Bahamas", 25.0, -77.4, ["nassau"]),
  country("BB", "Barbados", 13.2, -59.5, ["barbade", "bridgetown"]),
  country("BZ", "Belize", 17.2, -88.5, ["belmopan"]),
  country("BO", "Bolivia", -16.3, -63.6, ["bolivie", "bolivian", "bolivien", "la paz", "salar de uyuni", "uyuni"]),
  country("BR", "Brazil", -14.2, -51.9, ["bresil", "brazilian", "bresilien", "bresilienne", "brasilia", "sao paulo", "rio de janeiro", "belem", "lula"]),
  country("CA", "Canada", 56.1, -106.3, ["canadian", "canadien", "canadienne", "ottawa", "toronto", "calgary", "alberta", "oil sands", "sables bitumineux", "kitimat", "montreal", "quebec", "vancouver"]),
  country("CL", "Chile", -35.7, -71.5, ["chili", "chilean", "chilien", "chilienne", "santiago", "atacama", "escondida"]),
  country("CO", "Colombia", 4.6, -74.3, ["colombie", "colombian", "colombien", "bogota", "cartagena"]),
  country("CR", "Costa Rica", 9.7, -83.8, ["costa rican", "san jose"]),
  country("CU", "Cuba", 21.5, -77.8, ["cuban", "cubain", "havana", "la havane"]),
  country("DM", "Dominica", 15.4, -61.4, ["dominique", "roseau"]),
  country("DO", "Dominican Republic", 18.7, -70.2, ["republique dominicaine", "santo domingo"]),
  country("EC", "Ecuador", -1.8, -78.2, ["equateur", "ecuadorian", "equatorien", "quito", "guayaquil"]),
  country("SV", "El Salvador", 13.8, -88.9, ["salvadoran", "salvadorien", "san salvador"]),
  country("GD", "Grenada", 12.1, -61.7, ["grenade", "st george's"]),
  country("GT", "Guatemala", 15.8, -90.2, ["guatemalan", "guatemalteque", "guatemala city"]),
  country("GY", "Guyana", 4.9, -58.9, ["guyanese", "guyanais", "georgetown", "stabroek"]),
  country("HT", "Haiti", 19.0, -72.3, ["haitian", "haitien", "port-au-prince"]),
  country("HN", "Honduras", 15.2, -86.2, ["honduran", "hondurien", "tegucigalpa"]),
  country("JM", "Jamaica", 18.1, -77.3, ["jamaique", "jamaican", "jamaicain", "kingston"]),
  country("MX", "Mexico", 23.6, -102.6, ["mexique", "mexican", "mexicain", "mexicaine", "mexico city", "sheinbaum", "monterrey"]),
  country("NI", "Nicaragua", 12.9, -85.2, ["nicaraguan", "nicaraguayen", "managua"]),
  country("PA", "Panama", 8.5, -80.8, ["panamanian", "panameen", "panama city"]),
  country("PY", "Paraguay", -23.4, -58.4, ["paraguayan", "paraguayen", "asuncion", "itaipu"]),
  country("PE", "Peru", -9.2, -75.0, ["perou", "peruvian", "peruvien", "peruvienne", "lima", "callao", "las bambas"]),
  country("KN", "Saint Kitts and Nevis", 17.4, -62.8, ["saint kitts", "st kitts", "basseterre"]),
  country("LC", "Saint Lucia", 13.9, -61.0, ["sainte-lucie", "st lucia", "castries"]),
  country("VC", "Saint Vincent and the Grenadines", 13.0, -61.3, ["saint vincent", "st vincent", "kingstown"]),
  country("SR", "Suriname", 3.9, -56.0, ["surinam", "surinamese", "paramaribo"]),
  country("TT", "Trinidad and Tobago", 10.7, -61.2, ["trinidad", "trinite-et-tobago", "port of spain", "atlantic lng", "point lisas"]),
  country("US", "United States", 39.8, -98.6, ["us", "usa", "u.s.", "u.s", "united states", "etats-unis", "etats unis", "american", "americans", "americain", "americaine", "americains", "americaines", "washington", "white house", "maison blanche", "houston", "texas", "louisiana", "louisiane", "alaska", "gulf of mexico", "golfe du mexique", "golfe d'amerique", "gulf coast", "new york", "california", "californie", "pennsylvania", "north dakota", "oklahoma", "wyoming", "appalachia", "cushing", "corpus christi", "sabine pass", "trump", "biden", "congress", "senate", "capitol hill", "ferc", "doe", "epa", "us department of energy", "u.s. department of energy"]),
  country("UY", "Uruguay", -32.5, -55.8, ["uruguayan", "uruguayen", "montevideo"]),
  country("VE", "Venezuela", 6.4, -66.6, ["venezuelan", "venezuelien", "venezuelienne", "caracas", "maduro", "orinoco"]),
  // Asia and Middle East
  country("AF", "Afghanistan", 33.9, 67.7, ["afghan", "kabul", "kaboul", "taliban"]),
  country("AM", "Armenia", 40.1, 45.0, ["armenie", "armenian", "armenien", "yerevan", "erevan"]),
  country("AZ", "Azerbaijan", 40.1, 47.6, ["azerbaidjan", "azerbaijani", "azeri", "azerbaidjanais", "baku", "bakou", "shah deniz", "socar"]),
  country("BH", "Bahrain", 26.0, 50.6, ["bahrein", "bahraini", "bahreini", "manama", "bapco"]),
  country("BD", "Bangladesh", 23.7, 90.4, ["bangladeshi", "bangladais", "dhaka", "dacca", "chittagong"]),
  country("BT", "Bhutan", 27.5, 90.4, ["bhoutan", "thimphu"]),
  country("BN", "Brunei", 4.5, 114.7, ["bandar seri begawan"]),
  country("KH", "Cambodia", 12.6, 105.0, ["cambodge", "cambodian", "cambodgien", "phnom penh"]),
  country("CN", "China", 35.9, 104.2, ["chine", "chinese", "chinois", "chinoise", "beijing", "pekin", "shanghai", "shenzhen", "guangdong", "guangzhou", "tianjin", "xinjiang", "inner mongolia", "yunnan", "sichuan", "hebei", "xi jinping", "prc", "people's republic of china", "republique populaire de chine", "ndrc", "mainland china"]),
  country("CY", "Cyprus", 35.1, 33.4, ["chypre", "cypriot", "chypriote", "nicosia", "nicosie", "aphrodite gas"]),
  country("GE", "Georgia", 42.3, 43.4, ["georgie", "georgian", "tbilisi", "tbilissi"]),
  country("IN", "India", 20.6, 79.0, ["inde", "indian", "indien", "indienne", "new delhi", "delhi", "mumbai", "bombay", "jamnagar", "gujarat", "modi", "chennai", "bengaluru", "bangalore", "kolkata", "odisha", "rajasthan"]),
  country("ID", "Indonesia", -0.8, 113.9, ["indonesie", "indonesian", "indonesien", "indonesienne", "jakarta", "sulawesi", "kalimantan", "sumatra", "prabowo"]),
  country("IR", "Iran", 32.4, 53.7, ["iranian", "iranien", "iranienne", "tehran", "teheran", "kharg", "south pars", "khamenei", "pezeshkian", "nioc"]),
  country("IQ", "Iraq", 33.2, 43.7, ["irak", "iraqi", "irakien", "irakienne", "baghdad", "bagdad", "basra", "bassora", "kurdistan", "kirkuk", "erbil", "ceyhan pipeline", "somo"]),
  country("IL", "Israel", 31.0, 34.9, ["israel", "israeli", "israelien", "israelienne", "jerusalem", "tel aviv", "leviathan", "tamar field", "netanyahu", "haifa", "ashkelon"]),
  country("JP", "Japan", 36.2, 138.3, ["japon", "japanese", "japonais", "japonaise", "tokyo", "osaka", "nagoya", "fukushima", "kashiwazaki", "meti", "jera"]),
  country("JO", "Jordan", 30.6, 36.2, ["jordanie", "jordanian", "jordanien", "amman", "aqaba"]),
  country("KZ", "Kazakhstan", 48.0, 66.9, ["kazakh", "astana", "almaty", "tengiz", "kashagan", "karachaganak", "cpc pipeline", "caspian pipeline"]),
  country("KW", "Kuwait", 29.3, 47.5, ["koweit", "kuwaiti", "koweitien", "kuwait city", "kuwait petroleum", "kpc"]),
  country("KG", "Kyrgyzstan", 41.2, 74.8, ["kirghizistan", "kyrgyz", "bishkek"]),
  country("LA", "Laos", 19.9, 102.5, ["lao", "vientiane"]),
  country("LB", "Lebanon", 33.9, 35.9, ["liban", "lebanese", "libanais", "libanaise", "beirut", "beyrouth", "hezbollah"]),
  country("MY", "Malaysia", 4.2, 102.0, ["malaisie", "malaysian", "malaisien", "kuala lumpur", "sarawak", "sabah", "bintulu", "pengerang"]),
  country("MV", "Maldives", 3.2, 73.2, ["maldivian", "maldivien"]),
  country("MN", "Mongolia", 46.9, 103.8, ["mongolie", "mongolian", "mongol", "ulaanbaatar", "oulan-bator", "oyu tolgoi"]),
  country("MM", "Myanmar", 19.8, 96.0, ["birmanie", "burma", "burmese", "birman", "naypyidaw", "yangon", "rangoon"]),
  country("NP", "Nepal", 28.4, 84.1, ["nepalese", "nepali", "nepalais", "kathmandu", "katmandou"]),
  country("KP", "North Korea", 40.3, 127.5, ["coree du nord", "north korean", "nord-coreen", "pyongyang", "dprk", "kim jong un"]),
  country("OM", "Oman", 21.5, 55.9, ["omani", "omanais", "muscat", "mascate", "duqm", "sohar"]),
  country("PK", "Pakistan", 30.4, 69.3, ["pakistani", "pakistanais", "islamabad", "karachi", "lahore", "reko diq", "balochistan", "baluchistan"]),
  country("PH", "Philippines", 12.9, 121.8, ["philippine", "filipino", "philippin", "manila", "manille", "malampaya"]),
  country("QA", "Qatar", 25.4, 51.2, ["qatari", "qatarien", "qatarienne", "doha", "ras laffan", "north field"]),
  country("SA", "Saudi Arabia", 23.9, 45.1, ["arabie saoudite", "arabie", "saudi", "saudis", "saoudien", "saoudienne", "saoudiens", "riyadh", "riyad", "jeddah", "djeddah", "dhahran", "ras tanura", "yanbu", "jubail", "neom", "mbs", "mohammed bin salman", "abdulaziz bin salman", "jafurah"]),
  country("SG", "Singapore", 1.4, 103.8, ["singapour", "singaporean", "singapourien", "jurong"]),
  country("KR", "South Korea", 35.9, 127.8, ["coree du sud", "coree", "korea", "korean", "coreen", "coreenne", "seoul", "busan", "ulsan", "pohang", "kepco", "kogas"]),
  country("LK", "Sri Lanka", 7.9, 80.8, ["sri lankan", "srilankais", "colombo", "hambantota"]),
  country("SY", "Syria", 34.8, 39.0, ["syrie", "syrian", "syrien", "syrienne", "damascus", "damas", "banias"]),
  country("TJ", "Tajikistan", 38.9, 71.3, ["tadjikistan", "tajik", "dushanbe", "douchanbe"]),
  country("TH", "Thailand", 15.9, 101.0, ["thailande", "thai", "thailandais", "bangkok", "map ta phut"]),
  country("TL", "Timor-Leste", -8.9, 125.7, ["east timor", "timor oriental", "dili", "greater sunrise"]),
  country("TR", "Turkey", 39.0, 35.2, ["turkiye", "turquie", "turkish", "turc", "turque", "turcs", "ankara", "istanbul", "ceyhan", "erdogan", "botas", "izmir", "akkuyu", "sakarya gas"]),
  country("TM", "Turkmenistan", 39.0, 59.6, ["turkmen", "ashgabat", "achgabat", "galkynysh"]),
  country("AE", "United Arab Emirates", 23.4, 53.8, ["uae", "emirats arabes unis", "emirats", "emirates", "emirati", "emiratis", "emirien", "emirienne", "abu dhabi", "abou dabi", "abou dhabi", "dubai", "dubai", "ruwais", "fujairah", "sharjah", "mbz", "mohammed bin zayed", "das island"]),
  country("UZ", "Uzbekistan", 41.4, 64.6, ["ouzbekistan", "uzbek", "ouzbek", "tashkent", "tachkent"]),
  country("VN", "Vietnam", 14.1, 108.3, ["viet nam", "vietnamese", "vietnamien", "vietnamienne", "hanoi", "ho chi minh city", "ho chi minh ville", "haiphong"]),
  country("YE", "Yemen", 15.6, 48.5, ["yemen", "yemeni", "yemenite", "sanaa", "sana'a", "aden", "hodeidah", "hodeida", "ras isa", "bab el-mandeb", "bab al-mandab", "bab el mandeb", "bab al mandab"]),
  country("TW", "Taiwan", 23.7, 121.0, ["taiwanese", "taiwanais", "taiwanaise", "taipei", "hsinchu", "kaohsiung", "formosa"]),
  country("HK", "Hong Kong", 22.3, 114.2, ["hongkong", "hong-kong", "hongkongais"]),
  country("PS", "Palestine", 31.9, 35.2, ["palestinian", "palestinians", "palestinien", "palestinienne", "palestiniens", "gaza", "west bank", "cisjordanie", "ramallah", "hamas"]),
  // Europe
  country("AL", "Albania", 41.2, 20.2, ["albanie", "albanian", "albanais", "tirana"]),
  country("AD", "Andorra", 42.5, 1.6, ["andorre", "andorra la vella"]),
  country("AT", "Austria", 47.5, 14.6, ["autriche", "austrian", "autrichien", "autrichienne", "vienna", "vienne", "baumgarten"]),
  country("BY", "Belarus", 53.7, 28.0, ["bielorussie", "belarusian", "bielorusse", "minsk", "lukashenko", "mozyr"]),
  country("BE", "Belgium", 50.5, 4.5, ["belgique", "belgian", "belge", "belges", "antwerp", "anvers", "zeebrugge", "ghent", "gand", "doel", "tihange"]),
  country("BA", "Bosnia and Herzegovina", 43.9, 17.7, ["bosnie", "bosnia", "bosnian", "bosnien", "sarajevo"]),
  country("BG", "Bulgaria", 42.7, 25.5, ["bulgarie", "bulgarian", "bulgare", "sofia", "kozloduy", "burgas"]),
  country("HR", "Croatia", 45.1, 15.2, ["croatie", "croatian", "croate", "zagreb", "krk lng", "krk terminal"]),
  country("CZ", "Czechia", 49.8, 15.5, ["czech republic", "republique tcheque", "tchequie", "czech", "tcheque", "prague", "temelin", "dukovany"]),
  country("DK", "Denmark", 56.3, 9.5, ["danemark", "danish", "danois", "danoise", "copenhagen", "copenhague", "esbjerg", "bornholm"]),
  country("EE", "Estonia", 58.6, 25.0, ["estonie", "estonian", "estonien", "tallinn"]),
  country("FI", "Finland", 61.9, 25.7, ["finlande", "finnish", "finlandais", "finlandaise", "helsinki", "olkiluoto", "loviisa"]),
  country("FR", "France", 46.6, 2.2, ["french", "francais", "francaise", "francaises", "paris", "marseille", "fos-sur-mer", "fos sur mer", "le havre", "dunkerque", "dunkirk", "lyon", "lille", "bordeaux", "nantes", "toulouse", "strasbourg", "flamanville", "gravelines", "penly", "cattenom", "bugey", "tricastin", "lavera", "feyzin", "donges", "gonfreville", "hauts-de-france", "normandie", "bretagne", "occitanie", "auvergne-rhone-alpes", "macron", "bercy", "matignon", "elysee", "assemblee nationale", "cre", "ademe", "bayrou", "lecornu"]),
  country("DE", "Germany", 51.2, 10.5, ["allemagne", "german", "germans", "allemand", "allemande", "allemands", "berlin", "hamburg", "hambourg", "frankfurt", "francfort", "munich", "ruhr", "duisburg", "ludwigshafen", "wilhelmshaven", "brunsbuttel", "bavaria", "baviere", "north rhine-westphalia", "lower saxony", "merz", "scholz", "bundestag", "bundesnetzagentur"]),
  country("GR", "Greece", 39.1, 21.8, ["grece", "greek", "grec", "grecque", "athens", "athenes", "piraeus", "le piree", "alexandroupolis", "revithoussa"]),
  country("HU", "Hungary", 47.2, 19.5, ["hongrie", "hungarian", "hongrois", "hongroise", "budapest", "paks", "orban"]),
  country("IS", "Iceland", 65.0, -19.0, ["islande", "icelandic", "islandais", "reykjavik"]),
  country("IE", "Ireland", 53.4, -8.2, ["irlande", "irish", "irlandais", "irlandaise", "dublin", "moneypoint"]),
  country("IT", "Italy", 41.9, 12.6, ["italie", "italian", "italien", "italienne", "italiens", "rome", "milan", "milano", "trieste", "genoa", "genes", "taranto", "tarente", "sicily", "sicile", "sardinia", "sardaigne", "ravenna", "piombino", "meloni"]),
  country("LV", "Latvia", 56.9, 24.6, ["lettonie", "latvian", "letton", "riga"]),
  country("LI", "Liechtenstein", 47.2, 9.6, ["vaduz"]),
  country("LT", "Lithuania", 55.2, 23.9, ["lituanie", "lithuanian", "lituanien", "vilnius", "klaipeda"]),
  country("LU", "Luxembourg", 49.8, 6.1, ["luxembourgeois", "luxembourg city"]),
  country("MT", "Malta", 35.9, 14.4, ["malte", "maltese", "maltais", "valletta", "la valette"]),
  country("MD", "Moldova", 47.4, 28.4, ["moldavie", "moldovan", "moldave", "chisinau", "transnistria", "transnistrie"]),
  country("MC", "Monaco", 43.7, 7.4, ["monegasque"]),
  country("ME", "Montenegro", 42.7, 19.4, ["montenegrin", "podgorica"]),
  country("NL", "Netherlands", 52.1, 5.3, ["pays-bas", "pays bas", "dutch", "neerlandais", "neerlandaise", "hollande", "holland", "amsterdam", "rotterdam", "groningen", "groningue", "eemshaven", "maasvlakte", "pernis", "the hague", "la haye", "borssele"]),
  country("MK", "North Macedonia", 41.6, 21.7, ["macedoine du nord", "macedonia", "macedoine", "skopje"]),
  country("NO", "Norway", 60.5, 8.5, ["norvege", "norwegian", "norvegien", "norvegienne", "oslo", "stavanger", "bergen", "troll", "hammerfest", "barents", "north sea norway", "norwegian continental shelf", "snohvit", "nyhamna", "kollsnes", "mongstad"]),
  country("PL", "Poland", 51.9, 19.1, ["pologne", "polish", "polonais", "polonaise", "warsaw", "varsovie", "gdansk", "swinoujscie", "silesia", "silesie", "lubiatowo", "tusk", "gdynia"]),
  country("PT", "Portugal", 39.4, -8.2, ["portuguese", "portugais", "portugaise", "lisbon", "lisbonne", "sines", "porto"]),
  country("RO", "Romania", 45.9, 25.0, ["roumanie", "romanian", "roumain", "roumaine", "bucharest", "bucarest", "cernavoda", "constanta", "neptun deep"]),
  country("RU", "Russia", 61.5, 105.3, ["russie", "russian", "russians", "russe", "russes", "moscow", "moscou", "kremlin", "putin", "poutine", "siberia", "siberie", "sakhalin", "sakhaline", "yamal", "arctic lng", "arctic lng 2", "novorossiysk", "primorsk", "ust-luga", "murmansk", "urals crude", "ryazan", "novokuibyshevsk", "tuapse", "st petersburg", "saint-petersbourg", "vladivostok", "kaliningrad", "kremlin"]),
  country("SM", "San Marino", 43.9, 12.5, ["saint-marin"]),
  country("RS", "Serbia", 44.0, 21.0, ["serbie", "serbian", "serbe", "belgrade", "vucic", "nis serbia"]),
  country("SK", "Slovakia", 48.7, 19.7, ["slovaquie", "slovak", "slovaque", "bratislava", "mochovce", "bohunice", "fico"]),
  country("SI", "Slovenia", 46.2, 15.0, ["slovenie", "slovenian", "slovene", "ljubljana", "krsko"]),
  country("ES", "Spain", 40.5, -3.7, ["espagne", "spanish", "espagnol", "espagnole", "madrid", "barcelona", "barcelone", "bilbao", "algeciras", "huelva", "cartagena spain", "andalusia", "andalousie", "catalonia", "catalogne", "galicia", "galice", "sanchez", "red electrica", "almaraz", "cadiz"]),
  country("SE", "Sweden", 60.1, 18.6, ["suede", "swedish", "suedois", "suedoise", "stockholm", "gothenburg", "goteborg", "lulea", "boden", "skelleftea", "kiruna", "ringhals", "forsmark"]),
  country("CH", "Switzerland", 46.8, 8.2, ["suisse", "swiss", "geneva", "geneve", "zurich", "bern", "berne", "baar", "zug", "lausanne", "bale", "basel"]),
  country("UA", "Ukraine", 48.4, 31.2, ["ukrainian", "ukrainians", "ukrainien", "ukrainienne", "ukrainiens", "kyiv", "kiev", "odesa", "odessa", "kharkiv", "zaporizhzhia", "zaporijia", "donbas", "donetsk", "lviv", "dnipro", "zelensky", "zelenskyy", "zelensky", "ukrenergo", "naftogaz"]),
  country("GB", "United Kingdom", 55.4, -3.4, ["uk", "u.k.", "u.k", "united kingdom", "royaume-uni", "royaume uni", "britain", "great britain", "grande-bretagne", "british", "britannique", "britanniques", "britons", "england", "angleterre", "scotland", "ecosse", "scottish", "ecossais", "wales", "pays de galles", "northern ireland", "irlande du nord", "london", "londres", "aberdeen", "north sea uk", "uk north sea", "downing street", "westminster", "whitehall", "grangemouth", "port talbot", "scunthorpe", "teesside", "humber", "hinkley point", "sizewell", "heysham", "hartlepool", "starmer", "ofgem", "neso", "dogger bank"]),
  country("XK", "Kosovo", 42.6, 20.9, ["kosovar", "pristina", "prishtina"]),
  // Oceania
  country("AU", "Australia", -25.3, 133.8, ["australie", "australian", "australien", "australienne", "canberra", "sydney", "melbourne", "perth", "brisbane", "adelaide", "darwin", "pilbara", "gladstone", "queensland", "western australia", "new south wales", "victoria australia", "north west shelf", "gorgon", "browse basin", "scarborough gas", "albanese"]),
  country("FJ", "Fiji", -17.7, 178.1, ["fidji", "fijian", "suva"]),
  country("KI", "Kiribati", 1.9, -157.4, ["tarawa"]),
  country("MH", "Marshall Islands", 7.1, 171.2, ["iles marshall", "majuro"]),
  country("FM", "Micronesia", 7.4, 150.6, ["micronesie", "palikir"]),
  country("NR", "Nauru", -0.5, 166.9, ["yaren"]),
  country("NZ", "New Zealand", -40.9, 174.9, ["nouvelle-zelande", "nouvelle zelande", "new zealander", "neo-zelandais", "wellington", "auckland", "taranaki"]),
  country("PW", "Palau", 7.5, 134.6, ["palaos", "ngerulmud"]),
  country("PG", "Papua New Guinea", -6.3, 144.0, ["papouasie-nouvelle-guinee", "papouasie", "papua", "png lng", "port moresby"]),
  country("WS", "Samoa", -13.8, -172.1, ["samoan", "apia"]),
  country("SB", "Solomon Islands", -9.6, 160.2, ["iles salomon", "honiara"]),
  country("TO", "Tonga", -21.2, -175.2, ["tongan", "nuku'alofa"]),
  country("TV", "Tuvalu", -7.1, 177.6, ["funafuti"]),
  country("VU", "Vanuatu", -15.4, 167.0, ["port vila"]),
];

// ------------------------------------------------------------------ Companies

const COMPANIES: Entity[] = [
  // Oil and gas: majors, NOCs, LNG, services
  company("exxon", "ExxonMobil", "US", "oilgas", ["exxon", "exxon mobil"]),
  company("chevron", "Chevron", "US", "oilgas", ["hess"]),
  company("shell", "Shell", "GB", "oilgas", ["royal dutch shell", "shell plc"]),
  company("bp", "BP", "GB", "oilgas", ["bp", "bp plc", "british petroleum"]),
  company("totalenergies", "TotalEnergies", "FR", "oilgas", ["total energies", "totalenergie", "total se", "groupe total"]),
  company("eni", "Eni", "IT", "oilgas", ["eni spa", "plenitude"]),
  company("equinor", "Equinor", "NO", "oilgas", ["statoil"]),
  company("aramco", "Saudi Aramco", "SA", "oilgas", ["aramco", "arabian american oil"]),
  company("adnoc", "ADNOC", "AE", "oilgas", ["adnoc gas", "adnoc drilling", "xrg"]),
  company("qatarenergy", "QatarEnergy", "QA", "oilgas", ["qatar energy", "qatar petroleum", "qatargas"]),
  company("petrobras", "Petrobras", "BR", "oilgas"),
  company("gazprom", "Gazprom", "RU", "oilgas", ["gazprom neft", "gazprom export"]),
  company("rosneft", "Rosneft", "RU", "oilgas"),
  company("novatek", "Novatek", "RU", "oilgas"),
  company("lukoil", "Lukoil", "RU", "oilgas"),
  company("sonatrach", "Sonatrach", "DZ", "oilgas"),
  company("petronas", "Petronas", "MY", "oilgas"),
  company("cnpc", "CNPC", "CN", "oilgas", ["petrochina", "china national petroleum"]),
  company("sinopec", "Sinopec", "CN", "oilgas"),
  company("cnooc", "CNOOC", "CN", "oilgas"),
  company("ongc", "ONGC", "IN", "oilgas", ["oil and natural gas corporation"]),
  company("reliance", "Reliance Industries", "IN", "oilgas", ["reliance", "ambani"]),
  company("adani", "Adani", "IN", "power", ["adani group", "adani green", "adani power"]),
  company("repsol", "Repsol", "ES", "oilgas"),
  company("omv", "OMV", "AT", "oilgas", ["omv petrom"]),
  company("occidental", "Occidental", "US", "oilgas", ["occidental petroleum", "oxy"]),
  company("conocophillips", "ConocoPhillips", "US", "oilgas", ["conoco"]),
  company("woodside", "Woodside", "AU", "oilgas", ["woodside energy"]),
  company("santos", "Santos", "AU", "oilgas", ["santos ltd"]),
  company("inpex", "Inpex", "JP", "oilgas"),
  company("cheniere", "Cheniere", "US", "oilgas", ["cheniere energy"]),
  company("ventureglobal", "Venture Global", "US", "oilgas", ["venture global lng", "plaquemines", "calcasieu pass"]),
  company("freeportlng", "Freeport LNG", "US", "oilgas"),
  company("pemex", "Pemex", "MX", "oilgas"),
  company("pdvsa", "PDVSA", "VE", "oilgas"),
  company("nnpc", "NNPC", "NG", "oilgas", ["nnpc limited"]),
  company("dangote", "Dangote", "NG", "oilgas", ["dangote refinery", "dangote group"]),
  company("sonangol", "Sonangol", "AO", "oilgas"),
  company("ecopetrol", "Ecopetrol", "CO", "oilgas"),
  company("ypf", "YPF", "AR", "oilgas"),
  company("galp", "Galp", "PT", "oilgas", ["galp energia"]),
  company("orlen", "Orlen", "PL", "oilgas", ["pkn orlen"]),
  company("pertamina", "Pertamina", "ID", "oilgas"),
  company("ptt", "PTT", "TH", "oilgas", ["pttep", "ptt exploration"]),
  company("kazmunaygas", "KazMunayGas", "KZ", "oilgas", ["kazmunaigas", "kmg"]),
  company("technip", "Technip Energies", "FR", "oilgas", ["technip", "technipfmc"]),
  company("slb", "SLB", "US", "oilgas", ["schlumberger"]),
  company("halliburton", "Halliburton", "US", "oilgas"),
  company("bakerhughes", "Baker Hughes", "US", "oilgas"),
  company("saipem", "Saipem", "IT", "oilgas"),
  company("subsea7", "Subsea7", "GB", "oilgas", ["subsea 7"]),
  company("enbridge", "Enbridge", "CA", "oilgas"),
  company("tcenergy", "TC Energy", "CA", "oilgas", ["transcanada", "keystone xl"]),
  company("kindermorgan", "Kinder Morgan", "US", "oilgas"),
  company("snam", "Snam", "IT", "oilgas"),
  company("enagas", "Enagas", "ES", "oilgas"),
  company("fluxys", "Fluxys", "BE", "oilgas"),
  company("gasunie", "Gasunie", "NL", "oilgas"),
  company("grtgaz", "GRTgaz", "FR", "oilgas", ["terega"]),
  company("vitol", "Vitol", "CH", "markets"),
  company("trafigura", "Trafigura", "SG", "markets"),
  company("gunvor", "Gunvor", "CH", "markets"),
  company("mercuria", "Mercuria", "CH", "markets"),
  company("glencore", "Glencore", "CH", "industry"),
  // Utilities and grids
  company("edf", "EDF", "FR", "power", ["electricite de france", "edf energy", "edf renewables", "edf renouvelables"]),
  company("engie", "Engie", "FR", "power", ["gdf suez"]),
  company("enel", "Enel", "IT", "power", ["enel green power"]),
  company("iberdrola", "Iberdrola", "ES", "power", ["scottishpower", "scottish power", "avangrid"]),
  company("rwe", "RWE", "DE", "power"),
  company("eon", "E.ON", "DE", "power", ["e.on", "eon", "e-on"]),
  company("uniper", "Uniper", "DE", "power"),
  company("vattenfall", "Vattenfall", "SE", "power"),
  company("orsted", "Orsted", "DK", "renewables", ["oersted", "dong energy"]),
  company("sse", "SSE", "GB", "power", ["sse plc", "sse renewables"]),
  company("nationalgrid", "National Grid", "GB", "power", ["national grid plc"]),
  company("nextera", "NextEra", "US", "power", ["nextera energy", "florida power"]),
  company("duke", "Duke Energy", "US", "power"),
  company("fortum", "Fortum", "FI", "power"),
  company("enbw", "EnBW", "DE", "power"),
  company("endesa", "Endesa", "ES", "power"),
  company("naturgy", "Naturgy", "ES", "power"),
  company("tennet", "TenneT", "NL", "power"),
  company("rte", "RTE", "FR", "power", ["rte france", "reseau de transport d'electricite"]),
  company("enedis", "Enedis", "FR", "power"),
  company("terna", "Terna", "IT", "power"),
  company("cez", "CEZ", "CZ", "power", ["cez group"]),
  company("tepco", "TEPCO", "JP", "power", ["tokyo electric"]),
  company("acwa", "ACWA Power", "SA", "renewables", ["acwa"]),
  company("masdar", "Masdar", "AE", "renewables"),
  company("taqa", "TAQA", "AE", "power"),
  // Nuclear
  company("westinghouse", "Westinghouse", "US", "power", ["ap1000", "ap300"]),
  company("rosatom", "Rosatom", "RU", "power", ["atomstroyexport", "tvel"]),
  company("framatome", "Framatome", "FR", "power"),
  company("orano", "Orano", "FR", "power", ["areva"]),
  company("urenco", "Urenco", "GB", "power"),
  company("cameco", "Cameco", "CA", "power"),
  company("kazatomprom", "Kazatomprom", "KZ", "power"),
  company("nuscale", "NuScale", "US", "power", ["nuscale power"]),
  company("rollsroyce", "Rolls-Royce", "GB", "power", ["rolls royce", "rolls-royce smr"]),
  company("gehitachi", "GE Hitachi", "US", "power", ["bwrx-300", "bwrx 300"]),
  company("holtec", "Holtec", "US", "power"),
  // Renewables and cleantech
  company("vestas", "Vestas", "DK", "renewables"),
  company("siemensenergy", "Siemens Energy", "DE", "renewables", ["siemens gamesa", "gamesa"]),
  company("gevernova", "GE Vernova", "US", "renewables", ["ge vernova", "general electric"]),
  company("nordex", "Nordex", "DE", "renewables"),
  company("firstsolar", "First Solar", "US", "renewables"),
  company("longi", "LONGi", "CN", "renewables", ["longi green"]),
  company("jinko", "JinkoSolar", "CN", "renewables", ["jinko", "jinko solar"]),
  company("trina", "Trina Solar", "CN", "renewables", ["trina", "trinasolar"]),
  company("catl", "CATL", "CN", "renewables", ["contemporary amperex"]),
  company("byd", "BYD", "CN", "industry"),
  company("tesla", "Tesla", "US", "industry", ["musk", "elon musk"]),
  company("northvolt", "Northvolt", "SE", "renewables"),
  company("plugpower", "Plug Power", "US", "renewables"),
  company("nel", "Nel", "NO", "renewables", ["nel hydrogen", "nel asa"]),
  company("itm", "ITM Power", "GB", "renewables"),
  company("airliquide", "Air Liquide", "FR", "industry"),
  company("linde", "Linde", "DE", "industry", ["linde plc"]),
  company("fluence", "Fluence", "US", "renewables", ["fluence energy"]),
  company("neoen", "Neoen", "FR", "renewables"),
  company("voltalia", "Voltalia", "FR", "renewables"),
  company("enphase", "Enphase", "US", "renewables"),
  company("sungrow", "Sungrow", "CN", "renewables"),
  company("goldwind", "Goldwind", "CN", "renewables"),
  company("mingyang", "Mingyang", "CN", "renewables", ["ming yang"]),
  // Industry and materials
  company("arcelormittal", "ArcelorMittal", "LU", "industry", ["arcelor", "arcelor mittal", "mittal"]),
  company("thyssenkrupp", "Thyssenkrupp", "DE", "industry", ["thyssen", "tk", "tkse", "thyssenkrupp steel"]),
  company("tatasteel", "Tata Steel", "IN", "industry", ["tata"]),
  company("nipponsteel", "Nippon Steel", "JP", "industry"),
  company("baowu", "Baowu", "CN", "industry", ["china baowu", "baosteel"]),
  company("posco", "POSCO", "KR", "industry", ["posco holdings"]),
  company("ussteel", "US Steel", "US", "industry", ["u.s. steel", "united states steel"]),
  company("nucor", "Nucor", "US", "industry"),
  company("clevelandcliffs", "Cleveland-Cliffs", "US", "industry", ["cleveland cliffs"]),
  company("ssab", "SSAB", "SE", "industry"),
  company("salzgitter", "Salzgitter", "DE", "industry"),
  company("voestalpine", "Voestalpine", "AT", "industry"),
  company("riotinto", "Rio Tinto", "GB", "industry", ["riotinto"]),
  company("bhp", "BHP", "AU", "industry", ["bhp group", "bhp billiton"]),
  company("vale", "Vale", "BR", "industry", ["vale sa"]),
  company("angloamerican", "Anglo American", "GB", "industry", ["de beers"]),
  company("freeport", "Freeport-McMoRan", "US", "industry", ["freeport mcmoran", "freeport"]),
  company("codelco", "Codelco", "CL", "industry"),
  company("norskhydro", "Norsk Hydro", "NO", "industry", ["hydro asa"]),
  company("alcoa", "Alcoa", "US", "industry"),
  company("rusal", "Rusal", "RU", "industry", ["en+ group"]),
  company("chalco", "Chalco", "CN", "industry", ["chinalco", "aluminum corporation of china"]),
  company("albemarle", "Albemarle", "US", "industry"),
  company("sqm", "SQM", "CL", "industry", ["sociedad quimica y minera"]),
  company("umicore", "Umicore", "BE", "industry"),
  company("ega", "Emirates Global Aluminium", "AE", "industry", ["ega"]),
  company("basf", "BASF", "DE", "industry"),
  company("dow", "Dow", "US", "industry", ["dow inc", "dow chemical"]),
  company("lyondellbasell", "LyondellBasell", "NL", "industry", ["lyondell"]),
  company("ineos", "Ineos", "GB", "industry", ["ratcliffe"]),
  company("covestro", "Covestro", "DE", "industry"),
  company("solvay", "Solvay", "BE", "industry", ["syensqo"]),
  company("arkema", "Arkema", "FR", "industry"),
  company("yara", "Yara", "NO", "industry", ["yara international"]),
  company("ocp", "OCP", "MA", "industry", ["ocp group", "office cherifien des phosphates"]),
  company("holcim", "Holcim", "CH", "industry", ["lafarge", "lafargeholcim"]),
  company("heidelberg", "Heidelberg Materials", "DE", "industry", ["heidelbergcement", "heidelberg cement"]),
  company("saintgobain", "Saint-Gobain", "FR", "industry", ["saint gobain"]),
  company("airbus", "Airbus", "FR", "industry"),
  company("boeing", "Boeing", "US", "industry"),
  company("safran", "Safran", "FR", "industry"),
  company("thales", "Thales", "FR", "industry"),
  company("dassault", "Dassault", "FR", "industry", ["dassault aviation", "rafale"]),
  company("rheinmetall", "Rheinmetall", "DE", "industry"),
  company("leonardo", "Leonardo", "IT", "industry", ["leonardo spa"]),
  company("naval", "Naval Group", "FR", "industry"),
  company("volkswagen", "Volkswagen", "DE", "industry", ["vw", "audi", "porsche", "skoda"]),
  company("stellantis", "Stellantis", "NL", "industry", ["peugeot", "citroen", "fiat", "opel", "chrysler", "jeep"]),
  company("renault", "Renault", "FR", "industry", ["dacia", "ampere"]),
  company("toyota", "Toyota", "JP", "industry"),
  company("hyundai", "Hyundai", "KR", "industry", ["hyundai motor", "kia"]),
  company("mercedes", "Mercedes-Benz", "DE", "industry", ["mercedes", "mercedes benz", "daimler"]),
  company("bmw", "BMW", "DE", "industry"),
  company("generalmotors", "General Motors", "US", "industry", ["gm"]),
  company("ford", "Ford", "US", "industry", ["ford motor"]),
  company("schneider", "Schneider Electric", "FR", "industry", ["schneider"]),
  company("siemens", "Siemens", "DE", "industry", ["siemens ag", "siemens mobility"]),
  company("abb", "ABB", "CH", "industry"),
  company("alstom", "Alstom", "FR", "industry"),
  company("legrand", "Legrand", "FR", "industry"),
  company("nexans", "Nexans", "FR", "industry"),
  company("prysmian", "Prysmian", "IT", "industry"),
  company("hitachi", "Hitachi", "JP", "industry", ["hitachi energy"]),
  company("mitsubishi", "Mitsubishi", "JP", "industry", ["mitsubishi heavy", "mhi", "mitsubishi corp"]),
  company("maersk", "Maersk", "DK", "industry", ["a.p. moller", "moller-maersk"]),
  company("msc", "MSC", "CH", "industry", ["mediterranean shipping"]),
  company("cmacgm", "CMA CGM", "FR", "industry", ["cma-cgm", "saade"]),
  company("hapaglloyd", "Hapag-Lloyd", "DE", "industry", ["hapag lloyd"]),
  company("tsmc", "TSMC", "TW", "industry", ["taiwan semiconductor"]),
  company("samsung", "Samsung", "KR", "industry", ["samsung electronics", "samsung sdi"]),
  company("intel", "Intel", "US", "industry", ["intel corp"]),
  company("nvidia", "Nvidia", "US", "industry"),
  company("asml", "ASML", "NL", "industry"),
  company("stmicro", "STMicroelectronics", "CH", "industry", ["stmicro", "st micro", "stm"]),
  company("infineon", "Infineon", "DE", "industry"),
  company("micron", "Micron", "US", "industry", ["micron technology"]),
];

// ------------------------------------------------------------------ Commodities

const COMMODITIES: Entity[] = [
  commodity("crude", "Crude oil", "oilgas", ["crude", "brent", "wti", "petrole", "petrole brut", "baril", "barils", "oil price", "oil prices", "prix du petrole", "cours du petrole", "cours du brut", "brut", "oil market", "oil markets", "marche petrolier", "oil demand", "oil supply", "oil output", "oil production", "production petroliere", "arab light", "dated brent", "oil exports", "oil imports", "urals", "murban", "oil futures", "oil benchmark", "oil tanker", "oil tankers", "petrolier", "petroliers"]),
  commodity("natgas", "Natural gas", "oilgas", ["gas", "gaz", "natural gas", "gaz naturel", "lng", "gnl", "ttf", "henry hub", "jkm", "gas price", "gas prices", "prix du gaz", "lng cargo", "lng cargoes", "lng exports", "lng imports", "lng terminal", "lng terminals", "terminal methanier", "methanier", "methaniers", "feedgas", "gas storage", "stockage de gaz", "stockages de gaz", "gas supply", "gas supplies", "gas demand", "gas market", "gas markets", "gas flows", "gas pipeline", "gas field", "gas fields", "gas-fired", "gas plant", "gas plants", "gasfield", "biomethane", "biogas", "biogaz", "mtpa", "bcm", "bcf/d"]),
  commodity("coal", "Coal", "power", ["charbon", "thermal coal", "coking coal", "met coal", "metallurgical coal", "newcastle coal", "coal plant", "coal plants", "coal-fired", "coal power", "coal mine", "coal mines", "coal exports", "coal imports", "centrale a charbon", "centrales a charbon", "lignite"]),
  commodity("electricity", "Electricity", "power", ["electricite", "power price", "power prices", "electricity price", "electricity prices", "prix de l'electricite", "power market", "power markets", "marche de l'electricite", "spot power", "electricity market", "electricity demand", "power demand", "electricity supply", "power supply", "electricity bills", "power bills", "factures d'electricite", "facture d'electricite", "tarif reglemente", "epex", "day-ahead", "day ahead price", "mwh", "eur/mwh", "wholesale power", "wholesale electricity", "load growth", "power generation", "electricity generation", "production d'electricite", "ppa", "ppas", "power purchase agreement", "power purchase agreements"]),
  commodity("carbon", "Carbon", "renewables", ["eua", "euas", "ets", "eu ets", "ets2", "carbon price", "carbon prices", "prix du carbone", "carbon market", "carbon markets", "marche du carbone", "carbon credit", "carbon credits", "credits carbone", "carbon quota", "carbon quotas", "quotas carbone", "quotas d'emission", "quotas d'emissions", "carbon allowance", "carbon allowances", "carbon tax", "taxe carbone", "carbon offsets", "co2 price", "prix du co2", "carbon pricing", "tarification du carbone"]),
  commodity("uranium", "Uranium", "power", ["yellowcake", "u3o8", "enriched uranium", "uranium enrichi", "enrichment", "enrichissement", "nuclear fuel", "combustible nucleaire", "haleu"]),
  commodity("hydrogen", "Hydrogen", "renewables", ["hydrogene", "green hydrogen", "blue hydrogen", "hydrogene vert", "hydrogene bas carbone", "low-carbon hydrogen", "clean hydrogen", "electrolyser", "electrolysers", "electrolyzer", "electrolyzers", "electrolyseur", "electrolyseurs", "h2", "hydrogen hub", "hydrogen hubs", "hydrogen valley", "hydrogen valleys", "hydrogen bank", "e-fuels", "efuels", "e-methanol", "e-sngf"]),
  commodity("copper", "Copper", "industry", ["cuivre", "copper price", "copper prices", "copper mine", "copper mines", "copper smelter", "copper smelters", "copper concentrate", "copper cathode", "copper cathodes", "copper output", "copper demand", "copper supply"]),
  commodity("aluminium", "Aluminium", "industry", ["aluminum", "alumina", "bauxite", "aluminium smelter", "aluminum smelter", "aluminium smelters", "aluminum smelters"]),
  commodity("steel", "Steel", "industry", ["acier", "aciers", "hrc", "hot-rolled coil", "hot rolled coil", "steelmaker", "steelmakers", "steelmaking", "siderurgie", "siderurgique", "siderurgiste", "siderurgistes", "sidérurgie", "rebar", "steel mill", "steel mills", "steel plant", "steel plants", "acierie", "acieries", "blast furnace", "blast furnaces", "haut fourneau", "hauts fourneaux", "haut-fourneau", "hauts-fourneaux", "electric arc furnace", "electric arc furnaces", "green steel", "acier vert", "steel prices", "steel price", "steel imports", "steel exports", "steel output", "steel production", "steel industry", "steel sector", "flat steel", "long steel", "stainless steel", "steel safeguard", "steel safeguards", "steel tariff", "steel tariffs", "direct reduced iron"]),
  commodity("ironore", "Iron ore", "industry", ["iron-ore", "minerai de fer", "iron ore price", "iron ore prices", "iron ore exports", "iron ore imports", "iron ore mine", "iron ore mines", "iron ore shipments"]),
  commodity("nickel", "Nickel", "industry", ["nickel price", "nickel prices", "nickel mine", "nickel mines", "nickel smelter", "nickel smelters", "nickel pig iron", "nickel ore", "nickel sulphate", "nickel sulfate"]),
  commodity("lithium", "Lithium", "industry", ["lithium price", "lithium prices", "lithium carbonate", "lithium hydroxide", "spodumene", "lithium mine", "lithium mines", "lithium brine", "lithium project", "lithium projects", "lithium supply", "lithium demand", "lithium refinery", "lithium refineries"]),
  commodity("cobalt", "Cobalt", "industry", ["cobalt price", "cobalt prices", "cobalt mine", "cobalt mines", "cobalt exports", "cobalt supply"]),
  commodity("rareearths", "Rare earths and critical minerals", "industry", ["rare earths", "rare earth", "rare-earth", "rare-earths", "terres rares", "terre rare", "neodymium", "neodyme", "dysprosium", "praseodymium", "gallium", "germanium", "antimony", "critical minerals", "critical mineral", "mineraux critiques", "minerais critiques", "critical raw materials", "matieres premieres critiques", "permanent magnets", "aimants permanents", "rare earth magnets"]),
  commodity("gold", "Gold", "markets", ["gold price", "gold prices", "bullion", "once d'or", "cours de l'or", "prix de l'or", "gold miner", "gold miners", "gold mine", "gold mines", "gold rally", "gold record", "gold futures", "gold demand", "gold reserves", "or physique"]),
  commodity("gasoline", "Gasoline", "oilgas", ["petrol", "essence", "rbob", "gasoline price", "gasoline prices", "prix de l'essence", "prix a la pompe", "pump prices", "pump price", "fuel prices", "prix des carburants", "carburants", "carburant", "gasoline exports", "gasoline demand", "gasoline stocks", "motor fuel", "sp95", "sp98"]),
  commodity("diesel", "Diesel", "oilgas", ["gasoil", "gazole", "heating oil", "fioul", "fuel oil", "diesel price", "diesel prices", "prix du gazole", "diesel crack", "diesel cracks", "middle distillates", "ulsd", "marine fuel", "bunker fuel", "vlsfo", "biodiesel"]),
  commodity("jetfuel", "Jet fuel", "oilgas", ["kerosene", "kerosene", "carbureacteur", "saf", "sustainable aviation fuel", "carburant d'aviation", "carburant durable d'aviation", "jet fuel demand", "jet fuel prices", "aviation fuel"]),
  commodity("ammonia", "Fertiliser and ammonia", "industry", ["ammoniac", "ammonia", "fertiliser", "fertilizer", "fertilisers", "fertilizers", "engrais", "urea", "uree", "potash", "potasse", "phosphate", "phosphates", "nitrogen fertiliser", "nitrogen fertilizer", "green ammonia", "blue ammonia", "ammoniac vert", "ammonia plant", "ammonia plants", "ammonia exports", "ammonia imports", "fertiliser prices", "fertilizer prices", "prix des engrais"]),
  commodity("semiconductors", "Semiconductors", "industry", ["semiconductor", "semi-conducteur", "semi-conducteurs", "semiconducteur", "semiconducteurs", "chipmaker", "chipmakers", "puce electronique", "puces electroniques", "chip exports", "chip export", "chip industry", "chip sector", "chip plant", "chip plants", "chip factory", "chip factories", "fabs", "chip act", "chips act", "ai chips", "ai chip", "memory chips", "advanced chips"]),
];

// ------------------------------------------------------------------ Organisations

const ORGS: Entity[] = [
  org("eu", "European Union", ["eu", "ue", "union europeenne", "union europeene", "europe", "european", "europeen", "europeenne", "europeens", "europeennes", "eurozone", "zone euro", "eu27", "eu-27", "brussels", "bruxelles", "bloc europeen", "the bloc", "single market", "marche unique", "european commission", "commission europeenne", "european parliament", "parlement europeen", "european council", "conseil europeen", "conseil de l'ue", "eu commission", "eu council", "eu parliament", "von der leyen", "meps", "eurodeputes", "eurodeputes", "strasbourg parliament", "dg ener", "dg energy", "dg comp", "eu executive", "executif europeen", "entsog", "jorgensen", "sefcovic", "ribera", "hoekstra", "european court", "court of justice of the eu", "cjeu", "eib", "banque europeenne d'investissement", "european investment bank"], { iso2: "EU", lat: 50.8, lng: 4.4 }),
  org("opec", "OPEC", ["opec+", "opec plus", "opep", "opep+", "opep plus", "opec+ ministers", "opec members", "opec output", "opec cuts", "opec quotas", "opec basket", "opec meeting", "opec secretary", "al ghais", "jmmc", "cartel petrolier", "oil cartel"]),
  org("iea", "IEA", ["aie", "international energy agency", "agence internationale de l'energie", "fatih birol", "birol"]),
  org("fed", "Federal Reserve", ["federal reserve", "the fed", "fed rate", "fed rates", "fed chair", "fed cut", "fed cuts", "fed hike", "fed hikes", "fed meeting", "fed minutes", "fed officials", "fed policy", "fed funds", "fed decision", "fed signals", "fed holds", "fed pauses", "fomc", "powell", "reserve federale", "banque centrale americaine", "jerome powell", "fed's"]),
  org("ecb", "ECB", ["bce", "european central bank", "banque centrale europeenne", "lagarde", "christine lagarde", "ecb rate", "ecb rates", "ecb cut", "ecb hike", "ecb meeting", "ecb decision", "ecb's"]),
  org("imf", "IMF", ["fmi", "international monetary fund", "fonds monetaire international", "georgieva"]),
  org("wto", "WTO", ["omc", "world trade organization", "world trade organisation", "organisation mondiale du commerce", "okonjo-iweala"]),
  org("nato", "NATO", ["otan", "north atlantic treaty", "atlantic alliance", "alliance atlantique", "rutte"]),
  org("un", "United Nations", ["un", "onu", "united nations", "nations unies", "un security council", "security council", "conseil de securite", "un general assembly", "unga", "guterres", "antonio guterres", "un climate", "unfccc", "ipcc", "giec", "un report"]),
  org("cop", "COP climate summit", ["cop28", "cop29", "cop30", "cop31", "cop32", "cop 28", "cop 29", "cop 30", "cop 31", "cop 32", "climate summit", "sommet climat", "sommet sur le climat", "conference des parties", "un climate summit", "un climate talks", "climate talks", "paris agreement", "accord de paris", "ndc", "ndcs"]),
  org("g7", "G7", ["g7", "g-7", "group of seven", "g7 summit", "g7 leaders", "g7 ministers", "g7 price cap"]),
  org("g20", "G20", ["g-20", "group of twenty", "g20 summit", "g20 leaders"]),
  org("houthis", "Houthis", ["houthi", "houthistes", "houthiste", "rebelles houthis", "ansar allah", "ansarallah", "houthi rebels", "yemen rebels", "rebelles yemenites"]),
  org("bricsorg", "BRICS", ["brics", "brics+", "brics summit", "brics nations", "brics countries"]),
  org("gcc", "Gulf Cooperation Council", ["gcc", "gulf cooperation council", "conseil de cooperation du golfe", "ccg", "gulf states", "gulf producers", "gulf arab", "gulf arab states", "pays du golfe", "monarchies du golfe", "the gulf", "le golfe", "golfe persique", "persian gulf", "arabian gulf", "gulf region", "middle east producers"]),
  org("worldbank", "World Bank", ["world bank", "banque mondiale", "ifc", "international finance corporation", "banga"]),
  org("ebrd", "EBRD", ["ebrd", "berd", "european bank for reconstruction"]),
  org("entsoe", "ENTSO-E", ["entso e", "european tsos", "european grid operators"]),
];

// ------------------------------------------------------------------ Topics

const TOPICS: Entity[] = [
  topic("hormuz", "Strait of Hormuz", "policy", ["strait of hormuz", "detroit d'ormuz", "ormuz", "hormuz strait", "hormuz closure", "hormuz blockade"]),
  topic("redsea", "Red Sea", "policy", ["mer rouge", "red sea shipping", "red sea attacks", "red sea crisis", "red sea route", "bab el-mandeb strait", "gulf of aden", "golfe d'aden", "red sea diversions", "red sea disruption"]),
  topic("suez", "Suez Canal", "policy", ["suez", "canal de suez", "suez canal authority", "suez transit", "suez transits", "cape of good hope", "cap de bonne-esperance", "cape route"]),
  topic("panama", "Panama Canal", "policy", ["canal de panama", "panama canal authority", "panama canal transits", "panama canal drought", "gatun"]),
  topic("nordstream", "Nord Stream", "policy", ["nord stream 2", "nord stream 1", "nordstream", "nord-stream", "baltic pipeline sabotage", "nord stream sabotage"]),
  topic("tariffs", "Tariffs", "policy", ["tariff", "droits de douane", "droit de douane", "tarifs douaniers", "tarif douanier", "surtaxe", "surtaxes", "surtaxes douanieres", "customs duties", "customs duty", "import duties", "import duty", "import tariffs", "import tariff", "trade war", "guerre commerciale", "trade tariffs", "reciprocal tariffs", "section 232", "section 301", "anti-dumping", "antidumping", "anti-dumping duties", "countervailing duties", "trade barriers", "barrieres commerciales", "trade deal", "trade deals", "accord commercial", "trade talks", "negociations commerciales", "trade truce", "treve commerciale", "levies", "levy", "tariff hike", "tariff hikes", "tariff threat", "tariff threats", "tariff relief", "tariff exemption", "tariff exemptions", "quotas d'importation", "import quotas", "import quota", "safeguard measures", "mesures de sauvegarde", "trade dispute", "trade disputes", "differend commercial"]),
  topic("sanctions", "Sanctions", "policy", ["sanction", "sanctions package", "sanctions packages", "paquet de sanctions", "paquets de sanctions", "sanctions regime", "sanctioned", "sanctionne", "sanctionnee", "sanctionnes", "sanctions relief", "levee des sanctions", "ofac", "shadow fleet", "flotte fantome", "dark fleet", "secondary sanctions", "sanctions secondaires", "embargo", "embargoes", "blacklist", "blacklisted", "liste noire", "entity list", "designated entities", "asset freeze", "gel des avoirs", "snapback", "sanctions evasion", "contournement des sanctions", "oil embargo", "embargo petrolier", "russian oil ban", "russian gas ban", "sanctions on russia", "sanctions contre la russie", "sanctions on iran", "sanctions contre l'iran", "sanctions on venezuela", "maximum pressure", "pression maximale"]),
  topic("pricecap", "Oil price cap", "policy", ["price cap", "price caps", "plafonnement des prix", "plafonnement du prix", "plafond de prix", "oil price cap", "russian oil price cap", "g7 cap", "cap on russian oil", "prix plafond", "plafond du prix du petrole russe", "price ceiling", "price ceilings"]),
  topic("cbam", "CBAM", "policy", ["macf", "carbon border adjustment", "carbon border adjustment mechanism", "mecanisme d'ajustement carbone aux frontieres", "ajustement carbone aux frontieres", "carbon border tax", "carbon border levy", "taxe carbone aux frontieres", "border carbon"]),
  topic("ira", "Inflation Reduction Act", "policy", ["ira credits", "ira tax credits", "ira subsidies", "45x", "45v", "45q", "45y", "48e", "clean energy tax credits", "clean energy credits", "big beautiful bill", "one big beautiful bill", "obbba", "credits d'impot americains", "clean electricity credits", "production tax credit", "investment tax credit", "ptc", "itc"]),
  topic("greendeal", "Green Deal", "policy", ["pacte vert", "european green deal", "pacte vert europeen", "green deal industrial plan", "clean industrial deal", "pacte industriel propre", "fit for 55", "net-zero industry act", "net zero industry act", "nzia", "critical raw materials act", "crma", "european climate law", "loi climat europeenne", "2040 target", "objectif 2040", "eu climate target", "omnibus", "omnibus package", "affordable energy action plan", "action plan for affordable energy", "repowereu", "cbam review", "eu taxonomy", "taxonomie europeenne", "corporate sustainability", "csrd", "cs3d", "csddd", "eu methane regulation", "methane regulation", "reglement methane", "electricity market reform", "reforme du marche de l'electricite", "market design"]),
  topic("nuclear", "Nuclear power", "power", ["nucleaire", "nuclear power", "nuclear energy", "nuclear plant", "nuclear plants", "nuclear reactor", "nuclear reactors", "reactor", "reactors", "reacteur", "reacteurs", "centrale nucleaire", "centrales nucleaires", "energie nucleaire", "epr", "epr2", "epr 2", "nuclear fleet", "parc nucleaire", "nuclear restart", "nuclear restarts", "nuclear phase-out", "sortie du nucleaire", "nuclear revival", "nuclear renaissance", "nuclear newbuild", "nuclear new build", "new nuclear", "nouveau nucleaire", "pwr", "vver", "hualong", "nuclear waste", "dechets nucleaires", "nuclear fusion", "fusion nucleaire", "asnr", "iaea", "aiea", "grossi", "nuclear deal", "nuclear talks", "nuclear program", "nuclear programme", "programme nucleaire", "nuclear safety", "surete nucleaire", "nuclear capacity", "nuclear output", "nuclear generation", "nuclear industry", "industrie nucleaire", "filiere nucleaire"]),
  topic("smr", "Small modular reactors", "power", ["small modular reactor", "small modular reactors", "petits reacteurs modulaires", "petit reacteur modulaire", "smrs", "advanced reactor", "advanced reactors", "microreactor", "microreactors", "micro-reactor", "micro-reactors", "nuward", "x-energy", "terrapower", "newcleo", "jimmy energy", "amr programme", "modular reactor", "modular reactors", "reacteur modulaire", "reacteurs modulaires"]),
  topic("offshorewind", "Offshore wind", "renewables", ["eolien en mer", "eolien offshore", "eolien marin", "eoliennes en mer", "eoliennes offshore", "offshore wind farm", "offshore wind farms", "offshore wind project", "offshore wind projects", "offshore wind auction", "offshore wind auctions", "offshore wind tender", "offshore wind tenders", "floating wind", "eolien flottant", "wind farm", "wind farms", "parc eolien", "parcs eoliens", "wind turbine", "wind turbines", "eolienne", "eoliennes", "eolien", "eolien terrestre", "onshore wind", "wind power", "wind energy", "energie eolienne", "wind capacity", "wind auction", "wind auctions", "wind tender", "wind tenders", "wind lull", "dunkelflaute", "wind developer", "wind developers", "turbine maker", "turbine makers", "wind sector", "wind industry", "wind output", "wind generation"]),
  topic("solar", "Solar", "renewables", ["solaire", "solar power", "solar energy", "energie solaire", "photovoltaic", "photovoltaics", "photovoltaique", "photovoltaiques", "solar panel", "solar panels", "panneaux solaires", "panneau solaire", "solar farm", "solar farms", "parc solaire", "parcs solaires", "centrale solaire", "centrales solaires", "solar module", "solar modules", "modules solaires", "solar cell", "solar cells", "cellules solaires", "polysilicon", "polysilicium", "solar capacity", "solar installations", "solar tender", "solar tenders", "solar auction", "solar auctions", "solar project", "solar projects", "rooftop solar", "solaire en toiture", "agrivoltaics", "agrivoltaisme", "agrivoltaique", "solar output", "solar generation", "solar boom", "solar glut", "solar tariffs", "solar imports", "solar manufacturers", "solar makers", "utility-scale solar", "solar-plus-storage"]),
  topic("storage", "Battery storage", "renewables", ["battery storage", "stockage par batterie", "stockage par batteries", "stockage d'energie", "stockage d'electricite", "energy storage", "grid storage", "grid-scale storage", "grid scale storage", "utility-scale storage", "bess", "batteries", "battery", "batterie", "battery plant", "battery plants", "battery factory", "battery factories", "gigafactory", "gigafactories", "giga-usine", "gigausine", "battery maker", "battery makers", "battery cell", "battery cells", "cellules de batterie", "battery project", "battery projects", "battery capacity", "battery park", "lfp", "sodium-ion", "solid-state battery", "solid-state batteries", "batteries solides", "pumped hydro", "pumped storage", "long-duration storage", "long duration storage", "flow battery", "flow batteries", "battery supply chain", "battery materials", "battery recycling", "recyclage des batteries"]),
  topic("datacenters", "Data centers", "power", ["data center", "data centers", "data centre", "data centres", "datacenter", "datacenters", "datacentre", "datacentres", "centre de donnees", "centres de donnees", "hyperscaler", "hyperscalers", "ai power demand", "ai electricity demand", "ai data center", "ai data centers", "ai data centre", "ai data centres", "ai boom", "ai demand", "ai load", "compute demand", "hyperscale", "large flexible loads", "behind-the-meter", "behind the meter"]),
  topic("ev", "Electric vehicles", "renewables", ["ev", "evs", "electric vehicle", "electric vehicles", "vehicule electrique", "vehicules electriques", "voiture electrique", "voitures electriques", "electric car", "electric cars", "electric truck", "electric trucks", "electric bus", "electric buses", "ev sales", "ev demand", "ev market", "ev maker", "ev makers", "ev battery", "ev batteries", "ev charging", "charging station", "charging stations", "bornes de recharge", "borne de recharge", "recharge electrique", "charging network", "charging networks", "charging infrastructure", "plug-in hybrid", "plug-in hybrids", "hybrides rechargeables", "hybride rechargeable", "phev", "phevs", "ev tariffs", "ev subsidies", "ev tax credit", "ev tax credits", "ev adoption", "leasing social", "bonus ecologique", "zev mandate", "ev mandate", "combustion engine ban", "fin du moteur thermique", "moteur thermique", "electric mobility", "e-mobility", "mobilite electrique"]),
  topic("heatpumps", "Heat pumps", "renewables", ["heat pump", "heat pumps", "pompe a chaleur", "pompes a chaleur", "heat pump sales", "heat pump market", "heat pump subsidies", "boiler ban", "gas boiler", "gas boilers", "chaudiere a gaz", "chaudieres a gaz", "district heating", "reseau de chaleur", "reseaux de chaleur", "chauffage", "home heating", "heat decarbonisation", "heat decarbonization", "renovation energetique", "energy efficiency", "efficacite energetique", "maprimerenov", "building renovation", "renovation des batiments", "isolation thermique", "passoires thermiques", "passoire thermique", "geothermal", "geothermie", "geothermal energy", "geothermal heat"]),
  topic("grid", "Grid", "power", ["power grid", "power grids", "electricity grid", "electricity grids", "reseau electrique", "reseaux electriques", "grid operator", "grid operators", "gestionnaire de reseau", "gestionnaires de reseau", "transmission grid", "transmission line", "transmission lines", "ligne a haute tension", "lignes a haute tension", "high-voltage", "high voltage", "haute tension", "tres haute tension", "interconnector", "interconnectors", "interconnexion", "interconnexions", "grid connection", "grid connections", "raccordement", "raccordements", "grid queue", "connection queue", "interconnection queue", "grid upgrade", "grid upgrades", "grid investment", "grid investments", "grid expansion", "grid infrastructure", "grid capacity", "grid congestion", "congestion du reseau", "grid stability", "grid security", "grid reliability", "grid fees", "network charges", "tarif d'utilisation des reseaux", "turpe", "substation", "substations", "poste electrique", "postes electriques", "subsea cable", "subsea cables", "cable sous-marin", "cables sous-marins", "hvdc", "reseau de distribution", "smart grid", "smart grids", "reseau intelligent", "grid modernisation", "grid modernization", "grid resilience", "transmission operator", "transmission operators", "capacity market", "capacity mechanism", "mecanisme de capacite", "grid-forming", "grid forming", "negative prices", "prix negatifs"]),
  topic("blackout", "Blackout", "power", ["blackouts", "black-out", "black-outs", "power outage", "power outages", "power cut", "power cuts", "coupure de courant", "coupures de courant", "coupure d'electricite", "coupures d'electricite", "panne d'electricite", "pannes d'electricite", "panne electrique", "pannes electriques", "panne geante", "panne generale", "load shedding", "loadshedding", "delestage", "delestages", "rolling blackouts", "brownout", "brownouts", "grid collapse", "grid failure", "system collapse", "effondrement du reseau", "power failure", "power failures", "voltage surge", "voltage collapse", "cascading failure", "cascade de defaillances", "grid emergency", "grid alert", "emergency alert", "supply emergency", "capacity shortfall", "supply shortfall", "penurie d'electricite", "energy shortage", "electricity shortage", "electricity shortages", "power shortage", "power shortages", "power rationing", "rationnement", "restrictions d'electricite", "power restored", "electricite retablie", "courant retabli", "grid restored", "reseau retabli"]),
  topic("strike", "Strike", "industry", ["labor strike", "labour strike", "workers strike", "workers' strike", "general strike", "greve", "greves", "greve generale", "greviste", "grevistes", "mouvement social", "mouvements sociaux", "walkout", "walkouts", "walk out", "walked out", "union strike", "strike action", "strike actions", "on strike", "go on strike", "went on strike", "industrial action", "work stoppage", "work stoppages", "arret de travail", "arrets de travail", "debrayage", "debrayages", "preavis de greve", "appel a la greve", "strike ballot", "strike ballots", "strike threat", "strike threats", "picket line", "picket lines", "piquet de greve", "piquets de greve", "wage dispute", "wage disputes", "pay dispute", "pay disputes", "conflit social", "conflits sociaux", "labour dispute", "labor dispute", "labour disputes", "labor disputes", "union talks", "union negotiations", "collective bargaining", "negociations salariales", "port strike", "port strikes", "dockworkers strike", "dockers strike", "rail strike", "rail strikes", "refinery strike", "refinery strikes", "greve des raffineries", "greve dans les raffineries", "mine strike", "mine strikes", "miners strike", "miners' strike", "greve des mineurs", "plant strike", "unions", "syndicat", "syndicats", "cgt", "cfdt", "uaw", "ig metall", "ilwu", "teamsters", "united steelworkers", "usw", "united auto workers"]),
  topic("refinery", "Refining", "oilgas", ["refinery", "refineries", "raffinerie", "raffineries", "refiner", "refiners", "raffineur", "raffineurs", "refining", "raffinage", "refining margin", "refining margins", "marge de raffinage", "marges de raffinage", "crack spread", "crack spreads", "refinery run", "refinery runs", "refinery throughput", "refinery utilisation", "refinery utilization", "refinery outage", "refinery outages", "refinery fire", "refinery fires", "refinery closure", "refinery closures", "fermeture de raffinerie", "refinery maintenance", "refinery turnaround", "refinery turnarounds", "refinery restart", "refinery capacity", "refining capacity", "capacite de raffinage", "refinery expansion", "refinery upgrade", "refinery conversion", "petrochemical", "petrochemicals", "petrochimie", "petrochimique", "petrochimiques", "steam cracker", "steam crackers", "vapocraqueur", "vapocraqueurs", "naphtha", "naphta", "ethylene", "propylene", "polyethylene", "polypropylene", "olefins", "aromatics", "product exports", "product imports", "refined products", "produits raffines", "oil products", "produits petroliers", "fuel exports", "fuel imports", "distillate exports"]),
  topic("pipeline", "Pipelines", "oilgas", ["pipelines", "gazoduc", "gazoducs", "oleoduc", "oleoducs", "pipeline project", "pipeline projects", "pipeline capacity", "pipeline flows", "pipeline gas", "gas pipelines", "oil pipeline", "oil pipelines", "pipeline explosion", "pipeline attack", "pipeline attacks", "pipeline sabotage", "pipeline leak", "pipeline leaks", "pipeline deal", "pipeline expansion", "pipeline permit", "pipeline permits", "pipeline approval", "pipeline construction", "pipeline route", "pipeline routes", "gas transit", "transit gazier", "druzhba", "transmed", "medgaz", "tap pipeline", "trans adriatic", "tanap", "southern gas corridor", "corridor gazier sud", "power of siberia", "power of siberia 2", "force de la siberie", "eastmed", "midcat", "barmar", "h2med", "turkstream", "turkish stream", "blue stream", "yamal-europe", "brotherhood pipeline", "nigeria-morocco pipeline", "trans-saharan", "trans-saharan gas pipeline", "nigeria morocco pipeline", "eacop", "east african crude oil pipeline", "trans mountain", "trans mountain pipeline", "dakota access", "mountain valley pipeline", "colonial pipeline", "permian highway", "pipeline tariff", "pipeline tariffs", "tarif de transport", "hydrogen pipeline", "hydrogen pipelines", "hydrogen backbone", "european hydrogen backbone", "co2 pipeline", "co2 pipelines"]),
  topic("drilling", "Drilling and upstream", "oilgas", ["forage", "forages", "rig count", "rig counts", "drilling rig", "drilling rigs", "rigs", "oil rig", "oil rigs", "gas rig", "gas rigs", "drilling permit", "drilling permits", "permis de forage", "drilling licence", "drilling licences", "drilling license", "drilling licenses", "licensing round", "licensing rounds", "bid round", "bid rounds", "exploration licence", "exploration licences", "exploration license", "exploration licenses", "exploration permit", "exploration permits", "permis d'exploration", "exploration block", "exploration blocks", "offshore block", "offshore blocks", "offshore drilling", "forage offshore", "forage en mer", "deepwater", "deep water", "eaux profondes", "ultra-deepwater", "ultra deepwater", "exploration well", "exploration wells", "appraisal well", "appraisal wells", "wildcat", "wildcats", "oil discovery", "gas discovery", "decouverte petroliere", "decouverte gaziere", "oil find", "gas find", "oil field", "oil fields", "champ petrolier", "champs petroliers", "final investment decision", "fid", "upstream", "amont petrolier", "e&p", "exploration and production", "exploration-production", "fpso", "fpsos", "floating production", "subsea", "subsea tieback", "tieback", "tiebacks", "field development", "field development plan", "development plan", "plan de developpement", "first oil", "first gas", "premiere huile", "premier gaz", "plateau production", "production plateau", "wellhead", "wellheads", "horizontal well", "horizontal wells", "drilled but uncompleted", "ducs", "frac crew", "frac crews", "frac spread", "frac spreads", "pressure pumping", "oilfield services", "oilfield service", "services petroliers", "parapetrolier", "parapetroliers", "drillship", "drillships", "jackup", "jackups", "jack-up", "jack-ups", "semisub", "semisubs", "semi-submersible", "semi-submersibles", "day rate", "day rates", "dayrate", "dayrates", "rig contract", "rig contracts", "drilling contract", "drilling contracts", "drilling contractor", "drilling contractors", "upstream capex", "upstream investment", "upstream spending", "exploration spending", "exploration budget", "proven reserves", "proved reserves", "reserves prouvees", "reserve replacement", "reserves replacement", "decline rate", "decline rates", "output cut", "output cuts", "production cut", "production cuts", "output curbs", "production curbs", "output increase", "production increase", "output hike", "production hike", "output boost", "production boost", "output target", "production target", "output quota", "production quota", "output record", "production record", "record output", "record production", "output growth", "production growth", "production capacity", "spare capacity", "capacite de production", "capacite excedentaire"]),
  topic("shale", "Shale and tight oil", "oilgas", ["schiste", "shale oil", "shale gas", "petrole de schiste", "gaz de schiste", "tight oil", "tight gas", "huile de schiste", "shale producer", "shale producers", "shale driller", "shale drillers", "shale patch", "shale boom", "shale output", "shale production", "shale play", "shale plays", "shale basin", "shale basins", "shale well", "shale wells", "shale field", "shale fields", "shale revolution", "fracking", "fracturation hydraulique", "fracturation", "hydraulic fracturing", "permian", "permian basin", "bassin permien", "bakken", "eagle ford", "marcellus", "haynesville", "utica", "niobrara", "dj basin", "anadarko", "delaware basin", "midland basin", "vaca muerta shale", "neuquen", "neuquen basin", "bazhenov", "sichuan shale", "shale gas china", "shale gas argentina", "shale gas uk", "shale ban", "fracking ban", "fracking moratorium", "moratoire sur la fracturation", "interdiction de la fracturation", "shale independents", "shale consolidation", "shale m&a", "shale mergers", "shale deals", "shale capex", "shale spending", "shale discipline", "capital discipline", "shale investors", "shale returns", "shale cash flow", "shale breakeven", "shale breakevens", "breakeven", "breakevens", "breakeven price", "breakeven prices", "well productivity", "well costs", "drilling costs", "drilling efficiency", "rig efficiency", "rig productivity"]),
  topic("miningpermit", "Mining permits and projects", "industry", ["mining permit", "mining permits", "mining licence", "mining licences", "mining license", "mining licenses", "permis minier", "permis miniers", "permis d'exploitation", "permis d'exploitation miniere", "mining code", "code minier", "mining law", "loi miniere", "mining royalty", "mining royalties", "redevance miniere", "redevances minieres", "mining tax", "mining taxes", "taxe miniere", "mining approval", "mining approvals", "mine approval", "mine approvals", "mining project", "mining projects", "projet minier", "projets miniers", "new mine", "new mines", "nouvelle mine", "nouvelles mines", "mine opening", "mine openings", "mine closure", "mine closures", "fermeture de mine", "fermetures de mines", "mine expansion", "mine expansions", "mine restart", "mine restarts", "mine reopening", "mine collapse", "mine accident", "mine accidents", "mining accident", "mining accidents", "accident minier", "accidents miniers", "mining ban", "mining bans", "mining moratorium", "moratoire minier", "mining reform", "mining reforms", "reforme miniere", "mining nationalisation", "mining nationalization", "nationalisation miniere", "resource nationalism", "nationalisme des ressources", "mining dispute", "mining disputes", "mining contract", "mining contracts", "contrat minier", "contrats miniers", "mining deal", "mining deals", "mining agreement", "mining agreements", "accord minier", "accords miniers", "mining investment", "mining investments", "investissement minier", "investissements miniers", "mining sector", "secteur minier", "mining industry", "industrie miniere", "mining company", "mining companies", "compagnie miniere", "compagnies minieres", "societe miniere", "societes minieres", "minier", "miniers", "miniere", "minieres", "mining", "mines", "mine", "exploitation miniere", "extraction miniere", "deep-sea mining", "deep sea mining", "seabed mining", "exploitation miniere en eaux profondes", "exploitation des fonds marins", "international seabed authority", "the metals company", "polymetallic nodules", "nodules polymetalliques", "tailings", "tailings dam", "tailings dams", "residus miniers", "barrage de residus", "mine waste", "dechets miniers", "artisanal mining", "artisanal miners", "orpaillage", "orpailleurs", "illegal mining", "exploitation miniere illegale", "mineurs illegaux", "mining strike", "mining strikes", "mining protest", "mining protests", "mining community", "mining communities", "indigenous consultation", "indigenous consent", "consultation prealable", "environmental permit", "environmental permits", "permis environnemental", "environmental approval", "environmental approvals", "environmental review", "environmental impact", "etude d'impact", "environmental licence", "environmental license", "licence environnementale", "environmental assessment", "environmental assessments", "environmental clearance", "environmental clearances", "water permit", "water permits", "water licence", "water license", "water rights", "droits d'eau"]),
  topic("exportban", "Export bans and controls", "policy", ["export ban", "export bans", "export controls", "export control", "export restrictions", "export restriction", "export curbs", "export curb", "export licences", "export licenses", "export licence", "export license", "export licensing", "export permits", "export permit", "export quota", "export quotas", "export tax", "export taxes", "export duty", "export duties", "export levy", "export levies", "export halt", "export halts", "export suspension", "export suspensions", "export freeze", "export embargo", "export embargoes", "export limits", "export limit", "export cap", "export caps", "export moratorium", "interdiction d'exportation", "interdictions d'exportation", "interdiction des exportations", "restrictions a l'exportation", "restriction a l'exportation", "restrictions aux exportations", "controles a l'exportation", "controle des exportations", "controles des exportations", "licences d'exportation", "licence d'exportation", "quotas d'exportation", "quota d'exportation", "taxe a l'exportation", "taxes a l'exportation", "droits a l'exportation", "suspension des exportations", "gel des exportations", "embargo sur les exportations", "chip curbs", "chip export curbs", "chip export controls", "chip export ban", "chip restrictions", "tech export controls", "technology export controls", "dual-use", "dual use", "double usage", "biens a double usage", "entity listing", "unverified list", "foreign direct product rule", "fdpr", "export control regime", "regime de controle des exportations", "wassenaar", "mineral export ban", "mineral export bans", "ore export ban", "ore export bans", "raw material export ban", "raw material export bans", "nickel ore ban", "bauxite export ban", "cobalt export ban", "copper export ban", "lithium export ban", "gallium export controls", "germanium export controls", "rare earth export controls", "rare earths export controls", "rare earth export ban", "rare earths export ban", "rare earth curbs", "rare earths curbs", "graphite export controls", "antimony export controls", "tungsten export controls", "fuel export ban", "fuel export bans", "gasoline export ban", "diesel export ban", "product export ban", "coal export ban", "lng export ban", "lng export pause", "lng export moratorium", "lng export permits", "lng export approvals", "lng export licences", "lng export licenses", "lng permits", "lng approvals", "lng pause", "gas export ban", "gas export bans", "oil export ban", "oil export bans", "crude export ban", "crude export bans", "crude export halt", "crude export halts", "grain export ban", "food export ban", "fertiliser export ban", "fertilizer export ban", "urea export ban", "phosphate export ban", "export ban lifted", "export ban lift", "export ban extended", "export ban extension", "export ban ends", "export ban end", "export ban imposed", "export ban imposition", "export ban threat", "export ban threats"]),
  topic("carboncapture", "Carbon capture", "renewables", ["ccs", "ccus", "carbon capture", "capture du carbone", "captage du carbone", "captage de carbone", "carbon capture and storage", "carbon capture and utilisation", "carbon capture and utilization", "co2 storage", "stockage de co2", "stockage du co2", "co2 capture", "capture de co2", "captage de co2", "co2 transport", "transport de co2", "co2 hub", "co2 hubs", "northern lights", "porthos", "aramis", "hynet", "east coast cluster", "acorn", "greensand", "co2 injection", "injection de co2", "direct air capture", "captage direct", "carbon removal", "carbon removals", "elimination du carbone", "biochar", "beccs", "bioenergy with carbon capture"]),
  topic("shipping", "Shipping and freight", "industry", ["freight", "fret", "freight rates", "freight rate", "taux de fret", "tanker", "tankers", "tanker rates", "tanker market", "vlcc", "vlccs", "suezmax", "aframax", "lng tanker", "lng tankers", "lng carrier", "lng carriers", "lng shipping", "container shipping", "container rates", "container line", "container lines", "container ship", "container ships", "containership", "containerships", "porte-conteneurs", "transport maritime", "shipowner", "shipowners", "armateur", "armateurs", "shipyard", "shipyards", "chantier naval", "chantiers navals", "dry bulk", "bulk carrier", "bulk carriers", "vraquier", "vraquiers", "capesize", "baltic dry", "baltic dry index", "bunkering", "port congestion", "congestion portuaire", "port fees", "port fee", "port closure", "port closures", "shipping lane", "shipping lanes", "sea lane", "sea lanes", "route maritime", "routes maritimes", "chokepoint", "chokepoints", "choke point", "choke points", "strait of malacca", "malacca", "taiwan strait", "detroit de taiwan", "bosphorus", "bosphore", "turkish straits", "danish straits", "black sea", "mer noire", "black sea grain", "grain corridor", "imo", "international maritime organization", "organisation maritime internationale", "shipping emissions", "emissions maritimes", "green shipping", "shadow tanker", "shadow tankers", "dark tanker", "dark tankers", "piracy", "piraterie", "hijacked", "hijacking", "maritime security", "securite maritime", "aspides", "prosperity guardian", "seaborne", "seaborne exports", "seaborne imports", "shipping rates", "shipping costs", "shipping disruption", "shipping disruptions", "ship attack", "ship attacks", "vessel attack", "vessel attacks", "tanker attack", "tanker attacks", "tanker seized", "tanker seizure", "vessel seized", "navire saisi", "petrolier saisi"]),
];

// ------------------------------------------------------------------ Export

const ALL: Entity[] = [...COUNTRIES, ...COMPANIES, ...COMMODITIES, ...ORGS, ...TOPICS];

/** Every entity, grouped by kind in KIND_ORDER (stable within a kind). */
export const GAZETTEER: Entity[] = ALL.slice().sort(
  (a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind),
);

/**
 * Phrases the extractor consumes without tagging anything, so that a shorter
 * alias inside them cannot fire ("dow jones" is not the chemicals group).
 */
export const BLOCKED_PHRASES: string[] = [
  "dow jones",
  "dow futures",
  "dow industrials",
  "shell company",
  "shell companies",
  "vale of",
  "greenhouse gas",
  "greenhouse gases",
  "tear gas",
  "gas station",
  "gas stations",
  "market intel",
  "energy intel",
  "leonardo dicaprio",
  "leonardo da vinci",
  "harrison ford",
  "ford foundation",
  "bitcoin mining",
  "crypto mining",
  "data mining",
  "bitcoin mines",
  "amazon rainforest",
  "the amazon",
  "gold coast",
  "gold medal",
  "gold standard",
  "black gold",
  "rio grande",
  "vale do rio doce",
];
